name: BuildPlugin
on:
    push:
        branches:
            - main

jobs:
    build:
        uses: FriendsOfShopware/actions/.github/workflows/github.yml@main
        with:
            extensionName: ${{ github.event.repository.name }}
            shopwareVersion: '6.7.0'
            cliVersion: '0.6.34'
        secrets:
            ghToken: ${{ secrets.GITHUB_TOKEN }}
